---
dist: trusty
sudo: required

language: python
services:
  - docker

cache:
  bundler: true
  directories:
    - $HOME/.cache/pip
    - $HOME/.gilt/clone
    - $HOME/.inspec/cache

before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

install:
  - pip install molecule docker
  - bundle install --without=development --binstubs=vendor/bin

script:
  # Run tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
